interface TestimonialData {
  name: string;
  role: string;
  company: string;
  content: string;
  avatarUrl: string;
}

export const testimonialData: TestimonialData[] = [
  {
    name: "Sarah Johnson",
    role: "Marketing Director",
    company: "TechVision",
    content: "AIHub has revolutionized our content strategy. We're creating twice the content in half the time, and the analytics tools help us understand exactly what resonates with our audience.",
    avatarUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  },
  {
    name: "Michael Chen",
    role: "Data Scientist",
    company: "AnalyticsPro",
    content: "The data analysis capabilities are outstanding. I can process and visualize complex datasets in minutes instead of hours, and the insights generated by the AI have uncovered patterns we would have missed.",
    avatarUrl: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  },
  {
    name: "Alex Rodriguez",
    role: "Video Producer",
    company: "CreativeStream",
    content: "As a video content creator, AIHub's editing tools have been a game-changer. The automatic captioning, background removal, and enhancement features save me hours of work on every project.",
    avatarUrl: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  },
  {
    name: "Emma Wilson",
    role: "Operations Manager",
    company: "GlobalTech",
    content: "We've automated 70% of our repetitive tasks using AIHub's workflow tools. The team now focuses on strategic initiatives instead of manual processes, and our productivity has soared.",
    avatarUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  }
];